EnadeExperience/Controllers/DashEnadeController.cs
using EnadeExperience.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EnadeExperience.Controllers
{
    public class DashEnadeController : Controller
    {
        private DashEnadeViewModel _dashEnadeViewModel;

        public IActionResult AjusteTelaPrincipal()
        {
            _dashEnadeViewModel = new DashEnadeViewModel();
            ViewBag.ListaDash = _dashEnadeViewModel.ListaDash();

            return View();
        }

        [HttpPost]
        public IActionResult IncluirResultado(DashEnadeViewModel formulario)
        {
            formulario.Inserir();

            _dashEnadeViewModel = new DashEnadeViewModel();
            ViewBag.ListaDash = _dashEnadeViewModel.ListaDash();

            ViewBag.PopUpDash = formulario.PopUp;

            return View("AjusteTelaPrincipal");
        }

        [HttpGet]
        public IActionResult IncluirResultado(int? id)
        {
            if (id != null)
            {
                _dashEnadeViewModel = new DashEnadeViewModel();
                ViewBag.ListaDash = _dashEnadeViewModel.CarregarResultado(id);
            }

            return View();
        }

        [HttpGet]
        public IActionResult EditarResultado(int id)
        {
            _dashEnadeViewModel = new DashEnadeViewModel();
            _dashEnadeViewModel.Editar(id);

            return RedirectToAction("AjusteTelaPrincipal");
        }
        public IActionResult ExcluirResultado(int id)
        {
            _dashEnadeViewModel = new DashEnadeViewModel();
            _dashEnadeViewModel.Excluir(id);

            return RedirectToAction("AjusteTelaPrincipal");
        }
    }
}

EnadeExperience/Controllers/RelatoriosController.cs
using EnadeExperience.Models;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace EnadeExperience.Controllers
{
    public class RelatoriosController : Controller
    {
        private CursoViewModel _cursosViewModel;
        private DisciplinasViewModel _disciplinasViewModel;
        private QuestoesViewModel _questoesViewModel;

        public IActionResult FiltroQuestoes()
        {
            // Carrega as questões filtradas
            _questoesViewModel = new QuestoesViewModel();
            ViewBag.QuestoesFiltradas = _questoesViewModel.FiltrarQuestoes();

            // Dropdownlist da página
            _disciplinasViewModel = new DisciplinasViewModel();
            ViewBag.Disciplinas = _disciplinasViewModel.ListarDisciplinas();

            _cursosViewModel = new CursoViewModel();
            ViewBag.Cursos = _cursosViewModel.ListarCursos();

            return View();
        }

        [HttpPost]
        public IActionResult FiltrarQuestao(QuestoesViewModel formulario)
        {
            ViewBag.Resultado = 1;

            ViewBag.QuestoesFiltradas = formulario.FiltrarQuestoes();

            _disciplinasViewModel = new DisciplinasViewModel();
            ViewBag.Disciplinas = _disciplinasViewModel.ListarDisciplinas();

            _cursosViewModel = new CursoViewModel();
            ViewBag.Cursos = _cursosViewModel.ListarCursos();

            return View("FiltroQuestoes");
        }

        public IActionResult VisualizarPDF(QuestoesViewModel formulario)
        {
            return new ViewAsPdf("PDF", formulario.FiltrarQuestoes()) { FileName = "Enade Experience - Relatório PDF.pdf" };
        }

        public IActionResult VisualizarExcel(QuestoesViewModel formulario)
        {
            var questoes = formulario.FiltrarQuestoes();

            StringBuilder arquivo = new StringBuilder();

            arquivo.AppendLine("Questao;Resposta;Curso;Disciplinas;Dificuldade;Ano");

            foreach (var item in questoes)
            {
                arquivo.AppendLine(item.Questao + ";" + item.Resposta + ";" + item.Curso + ";" + item.Disciplina + " " + item.Disciplina2 + " " + item.Disciplina3 + " " + item.Disciplina4 + " " + item.Disciplina5 + ";" + item.Dificuldade + ";" + item.Ano);
            }

            var RecebeString = "";

            string regex = @"(<.+?>|&nbsp;)";

            RecebeString = Regex.Replace(arquivo.ToString(), regex, "").Trim();

            return File(Encoding.Latin1.GetBytes(RecebeString.ToString()), "text/csv", "Enade Experience - Relatório Excel.csv");

        }
        public IActionResult VisualizarProva(QuestoesViewModel formulario)
        {
            return new ViewAsPdf("Prova", formulario.FiltrarQuestoes()) { FileName = "Enade Experience - Prova PDF.pdf" };
        }
    }
}

EnadeExperience/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnadeExperience</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcut icon" type="imagex/png" href="~/imgs/LogoTipo.png">

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/ckeditor/ckeditor.js" charset="utf-8"></script>
</head>
<body onload="CarregarUsuarioLogado()">
    @*<header>
           <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EnadeExperience</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
        <div class="containerConteudo">
            <div class="container-fluido">
                <div class="wrapper">
                    <!-- Sidebar -->
                    <nav id="sidebar">
                        <div class="sidebarTopo">
                            <img src="/imgs/LogoTipo.png" alt="Enade Experience" width=120>
                        </div>
                        <hr />
                        <div class="sidebarTopoLabel">
                            @using Microsoft.AspNetCore.Http;
                            @inject IHttpContextAccessor HttpContextAccessor
                            <p>Seja Bem-vindo(a)<br /><div id="NomeUsuarioLogado"></div></p>
                        </div>
                        <ul class="list-group">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Página Principal</a>
                            </li>
                            <li>
                                <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Cursos</a>
                                <ul class="collapse list-unstyled" id="pageSubmenu">
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Cursos" asp-action="Cursos">• Consultar Cursos</a>
                                    </li>
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Cursos" asp-action="IncluirCurso">• Incluir Curso</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#pageSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Disciplinas</a>
                                <ul class="collapse list-unstyled" id="pageSubmenu1">
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Disciplinas" asp-action="Disciplinas">• Consultar Disciplinas</a>
                                    </li>
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Disciplinas" asp-action="IncluirDisciplina">• Incluir Disciplina</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Questões</a>
                                <ul class="collapse list-unstyled" id="pageSubmenu2">
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Questoes" asp-action="Questoes">• Consultar Questões</a>
                                    </li>
                                    <li>
                                        <a class="nav-link" asp-area="" asp-controller="Questoes" asp-action="IncluirQuestao">• Incluir Questão</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="Relatorios" asp-action="FiltroQuestoes">Relatórios</a>
                            </li>
                            <li>
                                <a class="nav-link" asp-area="" asp-controller="DashEnade" asp-action="AjusteTelaPrincipal">Ajuste P. Principal</a>
                            </li>

                            <br />

                            <li>
                                <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Index" asp-route-id="0">Sair</a>
                            </li>

                        </ul>
                        @*<footer>
                            <hr />
                            <p>&copy AdLeste - Todos os direitos reservados</p>
                        </footer>*@
                    </nav>
                </div>

                <div class="container">
                    <main role="main" class="conteudo">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
        @*<footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2021 - EnadeExperience - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>*@
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)

        <script>
            function CarregarUsuarioLogado() {
                var nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")'
                if (nome != "") {
                    var divNome = document.getElementById("NomeUsuarioLogado");
                    divNome.innerHTML = nome + "";
                }
                else {
                    window.location.href = '../Login/Index';
                }

            }
        </script>
</body>

</html>